In [1]:
import json
import pandas as pd

In [2]:
patients_data="patients.json"
finance_data="finance_details.json"
health_data="health_details.json"

In [3]:
try:
    with open(patients_data, 'r') as p:
        patients = p.read()

    with open(finance_data, 'r') as f:
        finance = f.read()

    with open(health_data, 'r') as h:
        health = h.read()

except FileNotFoundError:
    print("Data file not found.")
except Exception as e:
    print(f"An error occurred: {e}")

print(patients)

{
    "patients": [
        {
            "patientId": "P001",
            "firstName": "Rajesh",
            "lastName": "Kumar",
            "age": 34,
            "gender": "Male",
            "city": "Delhi",
            "contact": "9415632581"
        },
        {
            "patientId": "P002",
            "firstName": "Sunita",
            "lastName": "Sharma",
            "age": 28,
            "gender": "Female",
            "city": "Mumbai",
            "contact": "9854125763"
        },
        {
            "patientId": "P003",
            "firstName": "Amit",
            "lastName": "Patel",
            "age": 45,
            "gender": "Male",
            "city": "Bangalore",
            "contact": "9651245854"
        },
        {
            "patientId": "P004",
            "firstName": "Meera",
            "lastName": "Singh",
            "age": null,
            "gender": "Female",
            "city": "Chennai",
            "contact": "7451254638"
        },
        {
            "patientId": "P005",
            "firstName": "Ramesh",
            "lastName": "Gupta",
            "age": 50,
            "gender": "Male",
            "city": "Kolkata",
            "contact": null
        },
        {
            "patientId": "P006",
            "firstName": "Pooja",
            "lastName": "Verma",
            "age": 26,
            "gender": "Female",
            "city": "Jaipur",
            "contact": "6987451236"
        },
        {
            "patientId": "P007",
            "firstName": "Vikas",
            "lastName": "Yadav",
            "age": null,
            "gender": "Male",
            "city": "Pune",
            "contact": "7845123658"
        },
        {
            "patientId": "P008",
            "firstName": "Anita",
            "lastName": "Reddy",
            "age": 42,
            "gender": "Female",
            "city": "Hyderabad",
            "contact": "9845671230"
        },
        {
            "patientId": "P008",
            "firstName": "Anita",
            "lastName": "Reddy",
            "age": 42,
            "gender": "Female",
            "city": "Hyderabad",
            "contact": "9845671230"
        },
        {
            "patientId": "P009",
            "firstName": "Suresh",
            "lastName": "Singh",
            "age": null,
            "gender": "Male",
            "city": "Ahmedabad",
            "contact": null
        },
        {
            "patientId": "P010",
            "firstName": "Kavita",
            "lastName": "Joshi",
            "age": 29,
            "gender": "Female",
            "city": "Lucknow",
            "contact": "9890011223"
        }
    ]
}

In [4]:
with open(patients_data, 'r') as f:
    data = json.load(f)

# print(data)

for patient in data['patients']:
    print(f"Patient Name: {patient['firstName']} {patient['lastName']}, Age: {patient['age']}")

Patient Name: Rajesh Kumar, Age: 34
Patient Name: Sunita Sharma, Age: 28
Patient Name: Amit Patel, Age: 45
Patient Name: Meera Singh, Age: None
Patient Name: Ramesh Gupta, Age: 50
Patient Name: Pooja Verma, Age: 26
Patient Name: Vikas Yadav, Age: None
Patient Name: Anita Reddy, Age: 42
Patient Name: Anita Reddy, Age: 42
Patient Name: Suresh Singh, Age: None
Patient Name: Kavita Joshi, Age: 29

In [5]:
try:
    with open(patients_data, 'r') as f:
        data = json.load(f)

    with open(finance_data, 'r') as f:
        finance_data = json.load(f)

    with open(health_data, 'r') as f:
        health_data = json.load(f)
except FileNotFoundError as e:
    print(f"File not found: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

patient_df = pd.DataFrame(data['patients']) 
health_df = pd.DataFrame(health_data['healthRecords'])
finance_df = pd.DataFrame(finance_data['payments'])

In [6]:
def data_report(df):
    print(df.head())
    print("Data Summary:")
    print(df.describe(include='all'))
    print("Data Types:")
    print(df.dtypes)
    print("\nMissing Values:")
    print(df.isna().sum())
    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

In [7]:
print("Patient Data Report:")
data_report(patient_df)

Patient Data Report:
  patientId firstName lastName   age  gender       city     contact
0      P001    Rajesh    Kumar  34.0    Male      Delhi  9415632581
1      P002    Sunita   Sharma  28.0  Female     Mumbai  9854125763
2      P003      Amit    Patel  45.0    Male  Bangalore  9651245854
3      P004     Meera    Singh   NaN  Female    Chennai  7451254638
4      P005    Ramesh    Gupta  50.0    Male    Kolkata         NaN
Data Summary:
       patientId firstName lastName        age  gender       city     contact
count         11        11       11   8.000000      11         11           9
unique        10        10        9        NaN       2         10           8
top         P008     Anita    Singh        NaN  Female  Hyderabad  9845671230
freq           2         2        2        NaN       6          2           2
mean         NaN       NaN      NaN  37.000000     NaN        NaN         NaN
std          NaN       NaN      NaN   8.928286     NaN        NaN         NaN
min          NaN       NaN      NaN  26.000000     NaN        NaN         NaN
25%          NaN       NaN      NaN  28.750000     NaN        NaN         NaN
50%          NaN       NaN      NaN  38.000000     NaN        NaN         NaN
75%          NaN       NaN      NaN  42.750000     NaN        NaN         NaN
max          NaN       NaN      NaN  50.000000     NaN        NaN         NaN
Data Types:
patientId        str
firstName        str
lastName         str
age          float64
gender           str
city             str
contact          str
dtype: object

Missing Values:
patientId    0
firstName    0
lastName     0
age          3
gender       0
city         0
contact      2
dtype: int64

Duplicate Rows:
1

In [8]:
patient_df['age']=patient_df['age'].fillna(patient_df['age'].mean())
patient_df['contact']=patient_df['contact'].fillna('not provided')
patient_df['gender']=patient_df['gender'].replace({'Male': 'M', 'Female': 'F'})
patient_df=patient_df.drop_duplicates()

print("Cleaned Patient Data Report:")
print(patient_df)

Cleaned Patient Data Report:
   patientId firstName lastName   age gender       city       contact
0       P001    Rajesh    Kumar  34.0      M      Delhi    9415632581
1       P002    Sunita   Sharma  28.0      F     Mumbai    9854125763
2       P003      Amit    Patel  45.0      M  Bangalore    9651245854
3       P004     Meera    Singh  37.0      F    Chennai    7451254638
4       P005    Ramesh    Gupta  50.0      M    Kolkata  not provided
5       P006     Pooja    Verma  26.0      F     Jaipur    6987451236
6       P007     Vikas    Yadav  37.0      M       Pune    7845123658
7       P008     Anita    Reddy  42.0      F  Hyderabad    9845671230
9       P009    Suresh    Singh  37.0      M  Ahmedabad  not provided
10      P010    Kavita    Joshi  29.0      F    Lucknow    9890011223

In [9]:
cleaned_patient_df = patient_df.copy()

In [10]:
cleaned_patient_df

   patientId firstName lastName   age gender       city       contact
0       P001    Rajesh    Kumar  34.0      M      Delhi    9415632581
1       P002    Sunita   Sharma  28.0      F     Mumbai    9854125763
2       P003      Amit    Patel  45.0      M  Bangalore    9651245854
3       P004     Meera    Singh  37.0      F    Chennai    7451254638
4       P005    Ramesh    Gupta  50.0      M    Kolkata  not provided
5       P006     Pooja    Verma  26.0      F     Jaipur    6987451236
6       P007     Vikas    Yadav  37.0      M       Pune    7845123658
7       P008     Anita    Reddy  42.0      F  Hyderabad    9845671230
9       P009    Suresh    Singh  37.0      M  Ahmedabad  not provided
10      P010    Kavita    Joshi  29.0      F    Lucknow    9890011223

In [11]:
print("Patient Health Report:")
data_report(health_df)

Patient Health Report:
  patientId bloodGroup  heightCm  weightKg        disease   lastVisit
0      P001         B+       NaN      75.0   Hypertension  2026-05-10
1      P002         O+     160.0      58.0         Anemia  2026-04-22
2      P003         A+       NaN      82.0       Diabetes  2026-05-01
3      P004        AB+     155.0       NaN       Migraine  2026-05-18
4      P005         B-     170.0      85.0  Heart Disease  2026-03-30
Data Summary:
       patientId bloodGroup    heightCm   weightKg       disease   lastVisit
count         10          9    8.000000   8.000000            10          10
unique        10          7         NaN        NaN            10          10
top         P001         B+         NaN        NaN  Hypertension  2026-05-10
freq           1          2         NaN        NaN             1           1
mean         NaN        NaN  165.625000  72.500000           NaN         NaN
std          NaN        NaN    8.700369  13.212548           NaN         NaN
min          NaN        NaN  155.000000  55.000000           NaN         NaN
25%          NaN        NaN  159.500000  58.750000           NaN         NaN
50%          NaN        NaN  163.500000  76.500000           NaN         NaN
75%          NaN        NaN  171.250000  82.750000           NaN         NaN
max          NaN        NaN  180.000000  88.000000           NaN         NaN
Data Types:
patientId         str
bloodGroup        str
heightCm      float64
weightKg      float64
disease           str
lastVisit         str
dtype: object

Missing Values:
patientId     0
bloodGroup    1
heightCm      2
weightKg      2
disease       0
lastVisit     0
dtype: int64

Duplicate Rows:
0

In [12]:
health_df['bloodGroup']=health_df['bloodGroup'].fillna('Unknown')
health_df['heightCm']=health_df['heightCm'].fillna(health_df['heightCm'].mean())
health_df['weightKg']=health_df['weightKg'].fillna(health_df['weightKg'].mean())
health_df=health_df.drop_duplicates()

print("Cleaned Health Data Report:")
print(health_df)

Cleaned Health Data Report:
  patientId bloodGroup  heightCm  weightKg        disease   lastVisit
0      P001         B+   165.625      75.0   Hypertension  2026-05-10
1      P002         O+   160.000      58.0         Anemia  2026-04-22
2      P003         A+   165.625      82.0       Diabetes  2026-05-01
3      P004        AB+   155.000      72.5       Migraine  2026-05-18
4      P005         B-   170.000      85.0  Heart Disease  2026-03-30
5      P006         O-   162.000      55.0        Thyroid  2026-04-15
6      P007    Unknown   175.000      78.0         Asthma  2026-05-20
7      P008        AB-   158.000      72.5      Arthritis  2026-05-05
8      P009         B+   180.000      88.0        Obesity  2026-04-28
9      P010         O+   165.000      59.0           PCOS  2026-05-12

In [19]:
cleaned_health_df = health_df.copy()

In [13]:
print("Financial Data Report:")
data_report(finance_df)

Financial Data Report:
  patientId  billAmount paymentMode insurance    status
0      P001        2500         UPI       Yes      Paid
1      P002        1800         NaN        No      Paid
2      P003        3200        Card       Yes   Pending
3      P004        1500         UPI        No      Paid
4      P005        5000   Insurance       Yes  Approved
Data Summary:
       patientId   billAmount paymentMode insurance status
count         10    10.000000           8        10     10
unique        10          NaN           4         2      3
top         P001          NaN         UPI       Yes   Paid
freq           1          NaN           3         5      6
mean         NaN  2640.000000         NaN       NaN    NaN
std          NaN  1037.304198         NaN       NaN    NaN
min          NaN  1500.000000         NaN       NaN    NaN
25%          NaN  1950.000000         NaN       NaN    NaN
50%          NaN  2350.000000         NaN       NaN    NaN
75%          NaN  3075.000000         NaN       NaN    NaN
max          NaN  5000.000000         NaN       NaN    NaN
Data Types:
patientId        str
billAmount     int64
paymentMode      str
insurance        str
status           str
dtype: object

Missing Values:
patientId      0
billAmount     0
paymentMode    2
insurance      0
status         0
dtype: int64

Duplicate Rows:
0

In [15]:
finance_df['paymentMode']=finance_df['paymentMode'].fillna('Cash')
finance_df['insurance']=finance_df['insurance'].replace({'Yes': 'Y', 'No': 'N'})
finance_df=finance_df.drop_duplicates()
print("Cleaned Financial Data Report:")
print(finance_df)

Cleaned Financial Data Report:
  patientId  billAmount paymentMode insurance    status
0      P001        2500         UPI         Y      Paid
1      P002        1800        Cash         N      Paid
2      P003        3200        Card         Y   Pending
3      P004        1500         UPI         N      Paid
4      P005        5000   Insurance         Y  Approved
5      P006        2100        Cash         N      Paid
6      P007        2700        Card         Y   Pending
7      P008        1900        Cash         N      Paid
8      P009        3500         UPI         Y      Paid
9      P010        2200        Card         N   Pending

In [16]:
cleaned_finance_df = finance_df.copy()

In [20]:
cleaned_patient_df.to_csv('cleaned_patients.csv', index=False)
cleaned_health_df.to_csv('cleaned_health.csv', index=False)
cleaned_finance_df.to_csv('cleaned_finance.csv', index=False)

In [24]:
print("combined csv data")
combined_data=pd.merge(cleaned_patient_df, cleaned_health_df, on='patientId', how='inner')
combined_data=pd.merge(combined_data, cleaned_finance_df, on='patientId', how='inner')
combined_data.to_csv('combined_data.csv', index=False)
combined_data

combined csv data

,patientId,firstName,lastName,age,gender,city,contact,bloodGroup,heightCm,weightKg,disease,lastVisit,billAmount,paymentMode,insurance,status
0,P001,Rajesh,Kumar,34.0,M,Delhi,9415632581,B+,165.625,75.0,Hypertension,2026-05-10,2500,UPI,Y,Paid
1,P002,Sunita,Sharma,28.0,F,Mumbai,9854125763,O+,160.000,58.0,Anemia,2026-04-22,1800,Cash,N,Paid
2,P003,Amit,Patel,45.0,M,Bangalore,9651245854,A+,165.625,82.0,Diabetes,2026-05-01,3200,Card,Y,Pending
3,P004,Meera,Singh,37.0,F,Chennai,7451254638,AB+,155.000,72.5,Migraine,2026-05-18,1500,UPI,N,Paid
4,P005,Ramesh,Gupta,50.0,M,Kolkata,not provided,B-,170.000,85.0,Heart Disease,2026-03-30,5000,Insurance,Y,Approved
5,P006,Pooja,Verma,26.0,F,Jaipur,6987451236,O-,162.000,55.0,Thyroid,2026-04-15,2100,Cash,N,Paid
6,P007,Vikas,Yadav,37.0,M,Pune,7845123658,Unknown,175.000,78.0,Asthma,2026-05-20,2700,Card,Y,Pending
7,P008,Anita,Reddy,42.0,F,Hyderabad,9845671230,AB-,158.000,72.5,Arthritis,2026-05-05,1900,Cash,N,Paid
8,P009,Suresh,Singh,37.0,M,Ahmedabad,not provided,B+,180.000,88.0,Obesity,2026-04-28,3500,UPI,Y,Paid
9,P010,Kavita,Joshi,29.0,F,Lucknow,9890011223,O+,165.000,59.0,PCOS,2026-05-12,2200,Card,N,Pending